FROM docker-registry.default.svc:5000/sandbox-continuous-testing/jmeter-base-ikea:latest
# For local build from base image - FROM ikea/jmeter-base-ikea:latest
# SET VARIABLE $PROJECT to your project!!

MAINTAINER jens.pettersson

ARG JMETER_VERSION=5.3

WORKDIR $JMETER_HOME/bin
	
EXPOSE 60000
