kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  labels:
    build: influx-grafana-setup
  name: influx-grafana-setup
  namespace: ocp-pipelines-continuous-testing
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: ssh://git@git.build.ingka.ikea.com/continuous-testing/jmeter-distributed-ocp.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: config/influx_setup_Jenkinsfile.groovy
    type: JenkinsPipeline