apiVersion: v1
kind: ConfigMap
metadata:
  name: jmeter-load-test
  labels:
    app: jmeter
data:
  load_test: |
    #!/bin/bash
    #Script created to invoke jmeter test script for selenium
    #Script should be run like: ./load_test "path to the test script in jmx format"
    /jmeter/apache-jmeter-*/bin/jmeter -n -t /testdata/$1 -l /testdata/results.jtl -e -o /testdata/report -Jserver.rmi.ssl.disable=true