kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ct-data
  namespace: sandbox-continuous-testing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: netapp-qtree

